defaults:
  - _self_

# Input
labels_dir: ???

# Output
output_fp: ???

# Predictions
probabilities:
  undetermined: 0.5

# Pipeline
worker: 0
seed: 1

# Hydra
log_dir: ${output_fp}.logs
hydra:
  run:
    dir: "${log_dir}"
